#!/usr/bin/env bash

# Uses sv2v to convert system verilog to verilog

module=`basename -s .sv $1`
# Optional: include ../rtl/vendor.sv
# Optional: -I../vendor_lib/rtl/
sv2v --define=SYNTHESIS $1 > ${module}.v
